/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 030121022@std.izu.edu.tr
 */
public class HastaBilgiSistemi extends javax.swing.JFrame {

    /**
     * Creates new form HastaBilgiSistemi
     */
    public HastaBilgiSistemi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m_tc = new javax.swing.JTextField();
        m_ad = new javax.swing.JTextField();
        m_soyad = new javax.swing.JTextField();
        m_tani = new javax.swing.JTextField();
        m_poli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        m_listele = new javax.swing.JButton();
        m_ekle = new javax.swing.JButton();
        m_guncell = new javax.swing.JButton();
        m_sil = new javax.swing.JButton();
        m_yenile = new javax.swing.JButton();
        m_cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("TC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 30, 20));

        jLabel2.setText("ad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("soyad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setText("poliklinik");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("tanı");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        m_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tcActionPerformed(evt);
            }
        });
        getContentPane().add(m_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 20));

        m_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_adActionPerformed(evt);
            }
        });
        getContentPane().add(m_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, 20));
        getContentPane().add(m_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 20));
        getContentPane().add(m_tani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, 20));
        getContentPane().add(m_poli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "tc", "ad", "soyad", "tani", "poli"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 360, 190));

        m_listele.setText("listele");
        getContentPane().add(m_listele, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 20));

        m_ekle.setText("ekle");
        getContentPane().add(m_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, 20));

        m_guncell.setText("güncelle");
        m_guncell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_guncellActionPerformed(evt);
            }
        });
        getContentPane().add(m_guncell, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 20));

        m_sil.setText("sil");
        getContentPane().add(m_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 50, 20));

        m_yenile.setText("yenile");
        getContentPane().add(m_yenile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 80, 20));

        m_cikis.setText("cıkıs");
        m_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(m_cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_tcActionPerformed

    private void m_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_adActionPerformed

    private void m_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cikisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_cikisActionPerformed

    private void m_guncellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_guncellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_guncellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaBilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaBilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaBilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaBilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaBilgiSistemi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField m_ad;
    private javax.swing.JButton m_cikis;
    private javax.swing.JButton m_ekle;
    private javax.swing.JButton m_guncell;
    private javax.swing.JButton m_listele;
    private javax.swing.JTextField m_poli;
    private javax.swing.JButton m_sil;
    private javax.swing.JTextField m_soyad;
    private javax.swing.JTextField m_tani;
    private javax.swing.JTextField m_tc;
    private javax.swing.JButton m_yenile;
    // End of variables declaration//GEN-END:variables
}
